apiVersion: v2
appVersion: '1.0'
description: Helm chart for Waste and Waist Okteto
name: waste-and-waist-infra
type: application
version: 0.0.2
dependencies:
  - name: elasticsearch
    version: 8.5.1
    repository: https://helm.elastic.co
    condition: elasticsearch.enabled