apiVersion: v2
appVersion: '1.0'
description: Helm chart for Waste and Waist Okteto
name: ww-okteto-infra
type: application
version: 0.0.2
dependencies:
  - name: elasticsearch
    version: 7.17.3
    repository: https://helm.elastic.co
    condition: elasticsearch.enabled