apiVersion: v2
appVersion: '1.0'
description: Helm chart for Waste and Waist Okteto
name: waste-and-waist-infra
type: application
version: 0.0.2
dependencies:
  - name: elasticsearch
    version: 7.17.3
    repository: https://helm.elastic.co
    condition: elasticsearch.enabled
  - name: postgresql
    version: 13.2.5
    repository: https://charts.bitnami.com/bitnami
    condition: postgresql.enabled
  - name: mysql
    version: 9.14.3
    repository: https://charts.bitnami.com/bitnami
    condition: mysql.enabled