elasticsearch:
  enabled: false
  replicas: 2
  minimumMasterNodes: 1
  extraEnvs:
    - name: TZ
      value: Europe/Brussels
  imageTag: 7.17.3
  resources:
    limits:
      memory: 3072Mi
    requests:
      cpu: 20m
      memory: 1536Mi
  volumeClaimTemplate:
    resources:
      requests:
        storage: 1Gi
  ingress:
    enabled: true
    annotations:
      dev.okteto.com/generate-host: "true"
    className: ""
  fullnameOverride: elasticsearch-master
  sysctlInitContainer:
    enabled: false

postgresql:
  enabled: true
  fullnameOverride: postgres
  auth:
    postgresPassword: "Admin123"
    username: "postgres"
    password: "postgres"
    database: "ww"
  primary:
    persistence:
      size: 1Gi
  readReplicas:
    persistence:
      size: 1Gi

