clusterName: "elasticsearch"
nodeGroup: "master"

replicas: 1
minimumMasterNodes: 1

secret:
  password: "test123" # generated randomly if not defined

resources:
  requests:
    cpu: "1000m"
    memory: "1Gi"
  limits:
    cpu: "1000m"
    memory: "1Gi"

volumeClaimTemplate:
  accessModes: ["ReadWriteOnce"]
  resources:
    requests:
      storage: 1Gi

