replicas: 1
minimumMasterNodes: 1

secret:
  password: "Admin123" # generated randomly if not defined

volumeClaimTemplate:
  resources:
    requests:
      storage: 1Gi

sysctlInitContainer:
  enabled: false
