{{- /* @formatter:off */}}
#kind: StorageClass
#apiVersion: storage.k8s.io/v1
#metadata:
#     name: azure-disk
#provisioner: kubernetes.io/azure-disk
#parameters:
#  storageaccounttype: Standard_LRS
#  kind: Managed
#---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: mssql-data
{{- if .Values.persistence.annotations }}
  annotations:
{{ toYaml .Values.persistence.annotations | indent 4 }}
{{- end }}
  labels:
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    release: "{{ .Release.Name }}"
    heritage: "{{ .Release.Service }}"
spec:
  accessModes:
    - {{ .Values.persistence.dataAccessMode | quote }}
  resources:
    requests:
      storage: {{ .Values.persistence.dataSize | quote }}
{{- if .Values.persistence.storageClass }}
{{- if (eq "-" .Values.persistence.storageClass) }}
  storageClassName: ""
{{- else }}
  storageClassName: "{{ .Values.persistence.storageClass }}"
{{- end }}
{{- end }}
{{- if .Values.persistence.userdbSeparateClaim }}
---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: mssql-userdb
  {{- if .Values.persistence.annotations }}
annotations:
  {{ toYaml .Values.persistence.annotations | indent 4 }}
  {{- end }}
  labels:
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    release: "{{ .Release.Name }}"
    heritage: "{{ .Release.Service }}"
spec:
  accessModes:
    - {{ .Values.persistence.userdbaccessMode | quote }}
  resources:
    requests:
      storage: {{ .Values.persistence.userdbsize}}
{{- if .Values.persistence.storageClass }}
{{- if (eq "-" .Values.persistence.storageClass) }}
  storageClassName: ""
{{- else }}
  storageClassName: "{{ .Values.persistence.storageClass }}"
{{- end }}
{{- end }}
{{- end }}
{{- if .Values.persistence.userlogSeparateClaim }}
---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: mssql-log
{{- if .Values.persistence.annotations }}
  annotations:
{{ toYaml .Values.persistence.annotations | indent 4 }}
{{- end }}
  labels:
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    release: "{{ .Release.Name }}"
    heritage: "{{ .Release.Service }}"
spec:
  accessModes:
   - {{ .Values.persistence.userlogaccessMode | quote}}
  resources:
    requests:
      storage: {{ .Values.persistence.userlogsize}}
{{- if .Values.persistence.storageClass }}
{{- if (eq "-" .Values.persistence.storageClass) }}
  storageClassName: ""
{{- else }}
  storageClassName: "{{ .Values.persistence.storageClass }}"
{{- end }}
{{- end }}
{{- end }}
{{- if .Values.persistence.tempSeparateClaim }}
---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: mssql-temp
  {{- if .Values.persistence.annotations }}
annotations:
  {{ toYaml .Values.persistence.annotations | indent 4 }}
  {{- end }}
  labels:
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    release: "{{ .Release.Name }}"
    heritage: "{{ .Release.Service }}"
spec:
  accessModes:
   - {{ .Values.persistence.tempdbaccessMode | quote}}
  resources:
    requests:
      storage: {{ .Values.persistence.tempsize}}
{{- if .Values.persistence.storageClass }}
{{- if (eq "-" .Values.persistence.storageClass) }}
  storageClassName: ""
{{- else }}
  storageClassName: "{{ .Values.persistence.storageClass }}"
{{- end }}
{{- end }}
{{- end }}